### ISSUE TITLE
Depth order question

### ISSUE THREAD

**Issue by jbkarle** [Arthur151/CenterHMR#10]
Hi,
I need not the real depth but the order of the different depths. in your paper you mention ..." For people of different scales, the people with greater scale are in the front. For people of similar scale, the people with greater center confidence are in the front"...
My doubt is how you classify "different scales" & "similar scales".
(Maybe you have already coded that issue when selecting the rendering order of the different  masks/meshs; if so could you point where that code is?)
Many Thanks in advance!

**Comment by Arthur151** [comment]
Good question! Thanks for your interest in our work! 
As we all know, we estimate the 3-dim parameters of a weak-perspective camera model for 3D-to-2D projection and use 2D pose for supervision. The 3-dim camera parameters correspond to the scale, x-axis and y-axis translation of people in 2D images. We use the estimated scale with a distinguishable threshold to determine the "different scales" & "similar scales". Actually, in real cases, the center confidence is sufficient to determine the depth order of the crowd.

**Comment by jbkarle** [comment]
Thanks for the quick response & valuable comments!. Great work!

**Comment by nicolasugrinovic** [comment]
Hi, 
It is quite interesting that the model can give a depth order in this (implicit?) way!  That info is valuable for the reconstruction. 
Regarding this same issue. Can we recover the actual **3D scene depth** with your model? From this cam parameters can we get the actual (estimated) **absolute translation** (x,y,z in 3D space) of each person in the scene?

**Comment by Arthur151** [comment]
Thanks for your interests!
Given the specific intrinsic and extrinsic matrix of a camera, maybe we can convert the estimated weak-perspective camera parameters into the absolute translation you expected. 
We are working on a higher version that will directly give you the absolute translation of each person. 
I believe it will fit your request. And we hope it can be released soon.

**Comment by nicolasugrinovic** [comment]
In the case of images on-the-wild, how could you have the intrinsic camera? Would it work in that case?

**Comment by Arthur151** [comment]
Of course, it is realy hard to drive the intrinsic matrix from the in-the-wild image. Therefore, weare able to estimate the 'relative' absolute translation, instead of the real one.
The new version use the perspective camera.

**Comment by HuiliCui** [comment]
Hi，where can I get the 'relative' translation?
