### ISSUE TITLE
Visualization bug: OpenGL.error.GLError: GLError(err = 12289,

### ISSUE THREAD

**Issue by zhLawliet** [Arthur151/CenterHMR#11]
Visualization bug: OpenGL.error.GLError: GLError(err = 12289,baseOperation = eglMakeCurrent ....

The bug of pyrender is really a pain in the ass... ``bash

按照下面关于 centos 的解决办法，对我的linux系统（redHat） 无效，依然报上面的错
for centos
sudo yum install libXext libSM libXrender freeglut-devel

**Comment by Arthur151** [comment]
Sorry for the visualizatioin bugs of pyrender.
We have tried to re-implement the error but failed. Unfortunately, we don't have the redHat environment. We only test the code on Ubuntu and Centos.
Later, we will enrich the way of visualization to avoid the bugs of pyrender.
Currently, we find some fix ideas:
https://github.com/mmatl/pyrender/issues/7
Hope it help.
