### ISSUE TITLE
camera map

### ISSUE THREAD

**Issue by maminglang1991** [Arthur151/CenterHMR#12]
作者你好，请问在做训练数据的时候，camera map（1x3）是通过3dpw的ground truth中的哪些数据通过什么方式换算过来的呢？可否给你一个具体的公式呢？

**Comment by Arthur151** [comment]
We have update the arxiv with more details, please refer to 

[https://arxiv.org/abs/2008.12272](https://arxiv.org/abs/2008.12272)

Sorry for the belated response. Actually, we didn't directly supervise the camera map. Therefore, I can't provide a effective equation to derive the ground truth Camera map from 3dpw. But you may obtain the camare parameter for each person via fitting the back-projected 2D body joints. I can't guarantee  the effectiveness but it might worth a try.

Thanks for your interests! Have a nice day.
