### ISSUE TITLE
Video for ECCV workshop

### ISSUE THREAD

**Issue by FishWoWater** [Arthur151/CenterHMR#14]
Can you share the video / ppt for your presentation at eccv 2020 workshop? I am also interested in solutions from other teams. But I can not find related materials on the internet.

**Comment by Arthur151** [comment]
Sorry, we don't have the video. It's a pity that the organizer didn't record the workshop.

**Comment by FishWoWater** [comment]
Thanks for your quick response. I have one more question:  why researchers generally do not care depths of multiple people in one RGB image. Although figuring out absolute depths is ill-posed without knowing camera extrinsics & intrinsics, is there any possibility to determine the depth order among all the people in one RGB image?(e.g. normlise so that the depth of nearest person is 0, farthest person is 1). I am not sure if there is any existing work addressing this problem but I think it's meaningful and useful in AR/VR.   However, metrics like MPJPE do not care  depth at all. Could you list some related works or simply explain why the depth order isn't cared?  I read about your code and I think center confidence may not be enough to determine depths in the whole image since it's genally affected by occlusion.

**Comment by Arthur151** [comment]
Estimating Depth ordering is an interesting problem. Actually, we are working on it. I hope it would be usable function in CenterHMR. 
Currently, there are some mutli-person 3D pose (not mesh) estimation methods focus on monocular depth estimation. It is studied by us while it has been well explored by the researchers of that field (monocular depth estimation).

**Comment by FishWoWater** [comment]
Got it ~ Thanks a lot ~ Wish you all the best in future research.

**Comment by Arthur151** [comment]
Hope you enjoy it! 
Best.

**Comment by FishWoWater** [comment]
@Arthur151 Could you release your code for training?  TTTTThanks~

**Comment by Arthur151** [comment]
Thanks for your interets! We are preparing the training code. Hope we can release the complete code as soon as possible.

**Comment by FishWoWater** [comment]
@Arthur151 Alright, thanks
