### ISSUE TITLE
Order of body joints

### ISSUE THREAD

**Issue by ahsan3803** [Arthur151/CenterHMR#21]
I'm trying to draw body joints in 3D space using `3D SMPL joints` and `3D openpose joints` using CenterHMR. I followed SMPL joints order from [here](https://github.com/YeeCY/SMPLpp/blob/master/docs/media/kinematic_tree.png) and openpose order from [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-body_25)

I'm getting wrong 3D skeleton, could you share the right order of joints that CenterHMR outputs? Joints order is same with original SMPL or you changed joints order in output?

**Comment by Arthur151** [comment]
Please refer to src/constants.py.
The code saves two kind of joints, [OpenPose_25](https://github.com/Arthur151/CenterHMR/blob/00c43337855c41fffae7ea552dda9be05cacd282/src/constants.py#L12) and [SMPL_24](https://github.com/Arthur151/CenterHMR/blob/00c43337855c41fffae7ea552dda9be05cacd282/src/constants.py#L18).

I think the order is same as you provide.
Actually, you can get any joint you want via regressing from the estimated SMPL body mesh.

**Comment by Arthur151** [comment]
You may use [draw_skeleton](https://github.com/Arthur151/CenterHMR/blob/00c43337855c41fffae7ea552dda9be05cacd282/src/visualization/visualization.py#L196) and refer to 
`org_img = draw_skeleton(org_img, kp2d_vis, bones=constants.body25_connMat, cm=constants.cm_body25)`

**Comment by ahsan3803** [comment]
Thanks for your prompt response. I have solved the problem. Order is same as I mentioned above, there was minor mistake in my code. Now I can get right 3D skeleton of SMPL and OpenPose using CenterHMR results in Mayavi.
