### ISSUE TITLE
Can it run on Windows/MOS ? 

### ISSUE THREAD

**Issue by KleanOcean** [Arthur151/CenterHMR#25]
Impressive project, I want to run on Windows, however windows seems donot have the EGL library as required.
However I have encountered this issue:
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)
Does the openGL library necessary and do the code can run on windows ?

**Comment by KleanOcean** [comment]
The problem is solved.

I did the following things to make it run on Windows

1. comment out line 19 in render.py  # os.environ['PYOPENGL_PLATFORM'] = 'egl'
2. replace the make_uncurrent(self) function to     : 
    def make_uncurrent(self):
        # import pyglet
        # pyglet.gl.xlib.glx.glXMakeContextCurrent(self._window.context.x_display, 0, 0, None)
        try:
            import pyglet.gl.xlib
            pyglet.gl.xlib.glx.glXMakeContextCurrent(self._window.context.x_display, 0, 0, None)
        except:
            pass
3. change all the '/' to '\\' when specifying paths.

**Comment by Arthur151** [comment]
Thanks for your valuable comments.

**Comment by MhmdAliChamass99** [comment]
@KleanOcean can you please tell me the path for this file (render.py)
