### ISSUE TITLE
revert values

### ISSUE THREAD

**Issue by lisa676** [Arthur151/CenterHMR#26]
@Arthur151  I have a question. In the final outputs of 25 3D op_joints, I want to revert/reverse the values of Z. Kindly update me that how to do it?  
And if I want to revert the values of all axis (X, Y and Z) then how I can change it?  

Waiting for response.

**Comment by Arthur151** [comment]
What do you mean by 'revert'? If you try to flip the keypoints along z axis, please try to use:
`op_joints[:,:,-1] *= -1`

For all axis, please use:
`op_joints *= -1`

**Comment by lisa676** [comment]
Yes my meaning was flip. Thanks for fast reply.

**Comment by lisa676** [comment]
@Arthur151 How we can export or get 2D results/skeleton from body center in ROMP? Body center is new way to estimation the pose but I'm unable to get only 2D. I want to visualize 2D skeletal results. Would you like to shine something on this problem? 
Thanks

**Comment by Arthur151** [comment]
I'm sorry. What do you mean by geting 2D results/skeleton from body center?
I have just commited a new version which whill save the back-projected 2D pose, 'pj2d' in npz. Please update your code.

**Comment by Arthur151** [comment]
I'm sorry. What do you mean by geting 2D results/skeleton from body center?
I have just commited a new version which whill save the back-projected 2D pose, 'pj2d' in npz. Please update your code.
