### ISSUE TITLE
Visualizing projected 2D keypoints on the original image

### ISSUE THREAD

**Issue by ericwang0701** [Arthur151/CenterHMR#27]
Thank you for sharing your amazing work. I have tried to visualize the projected 2d keypoints (i.e. `pj2d`) on the original image. 
Taking the `3dpw_sit_on_street.jpg` sample image as an example. Since `pj2d` are normalized (-1~1) coordinates on the input image size (512x 512), I first compute their corresponding image coordinate in the original image size (1920x1080) by:
`pj2d= (pj2d+ [1,1]) / 2 * [1920, 1080]`

Then I plotted those keypoints on the original image. However, it seems there is an offset on the y-axis (i.e. height). All the keypoints are lower than the positions where they should be.
![image](https://drive.google.com/uc?export=view&id=15082JwVRCEGj1e9VoQdvOouUIbUVsfbL)

Any thoughts on how to compute and visualize projected 2D keypoints correctly would be really appreciated.

**Comment by Arthur151** [comment]
The bug could be easily fixed by replace 
`pj2d= (pj2d+ [1,1]) / 2 * [1920, 1080]`
with 
`pj2d= (pj2d+ [1,1]) / 2 * [1920, 1920]`

The reason is that the input image is a square.
Thanks for your interest! Best.

**Comment by donguk-dev** [comment]
Hello, I had same problem but I solved it.
here is solution code.

stride = max(H,W)
pj2d_results[batch_idx]= (pj2d_results[batch_idx]+1.0)/2*stride
                j = pj2d_results[batch_idx][0] 
                img = cv2.circle(img,(int(j[0]),(int(j[1]-(W-H)/2))),10,(0,0,255),-1

**Comment by donguk-dev** [comment]
> The bug could be easily fixed by replace
> `pj2d= (pj2d+ [1,1]) / 2 * [1920, 1080]`
> with
> `pj2d= (pj2d+ [1,1]) / 2 * [1920, 1920]`
> 
> The reason is that the input image is a square.
> Thanks for your interest! Best.

You should fix it!
thank you for your code.

**Comment by Arthur151** [comment]
Thanks for your contribution! I will fix it in the next commit.
