### ISSUE TITLE
Question about the pretrained model

### ISSUE THREAD

**Issue by Deanplayerljx** [Arthur151/CenterHMR#29]
Hi,

Can I know if the currently released pretrained model has been trained on 3dpw or not? Thanks!

**Comment by Arthur151** [comment]
Thanks for your interest! 
It wasn't trained on 3dpw.
I have a version which has been trained on the train set of 3dpw, which has way more better performance on 3dpw.

**Comment by Deanplayerljx** [comment]
Got you. Thanks for the quick reply!
