### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by seonghyunkim1212** [Arthur151/CenterHMR#6]
Thank you for your awesome work!
I have one question.
Do you have plans to upload the training code?

**Comment by Arthur151** [comment]
Thanks for your interests! Yes, we do have a plan to release the training code. Currently, the method is not completed yet, just V0.0 for demo testing. We will release the train code V2.0 after solving some weakness. Besides, our team is also working on the runtime optimization V1.0. They will be gradually open sourced.

**Comment by seonghyunkim1212** [comment]
Thank you for quick reply!

Could you share eft smpl parameters for posetrack dataset?

**Comment by Arthur151** [comment]
Sorry, I don't have it. Please contact the author.

**Comment by seonghyunkim1212** [comment]
Got it, Thanks!
