### ISSUE TITLE
Colab Demo not working

### ISSUE THREAD

**Issue by jbkarle** [Arthur151/CenterHMR#9]
Cell "!CUDA_VISIBLE_DEVICES=0 python core/test.py --gpu=0 --configs_yml=configs/basic_test_video.yml"
Outputs:
----------------
Configuration:
{'tab': 'test', 'configs_yml': 'configs/basic_test_video.yml', 'demo_image_folder': '../demo/videos/Messi_1', 'multi_person': True, 'use_coordmaps': True, 'head_conv_block_num': 2, 'kp3d_format': 'smpl24', 'eval': False, 'max_person': 16, 'BN_type': 'BN', 'Rot_type': '6D', 'center_idx': 1, 'centermap_size': 64, 'HMloss_type': 'MSE', 'model_precision': 'fp32', 'baseline': 'hrnetv5', 'input_size': 512, 'gmodel_path': '../trained_models/pw3d_81.8_58.6.pkl', 'best_save_path': '', 'print_freq': 50, 'epoch': 300, 'fine_tune': True, 'lr': 0.0003, 'weight_decay': 1e-05, 'gpu': '0', 'batch_size': 64, 'val_batch_size': 8, 'nw': 4, 'dataset_rootdir': '/content/dataset/', 'dataset': 'h36m,mpii,coco,aich,up,ochuman,lsp,movi', 'voc_dir': '/content/dataset/VOCdevkit/VOC2012/', 'high_resolution': True, 'save_best_folder': '/content/checkpoints/', 'log_path': '/content/log/', 'total_param_count': 85, 'smpl_model_path': '/content/CenterHMR/models', 'adjust_lr_epoch': [], 'kernel_sizes': [5], 'GPUS': 0, 'save_mesh': False, 'save_centermap': False, 'save_dict_results': False, 'webcam': False}
----------------
Traceback (most recent call last):
  File "core/test.py", line 4, in <module>
    from utils.multiprocess import * #Multiprocess
  File "/content/CenterHMR/src/utils/multiprocess.py", line 9, in <module>
    from utils.demo_utils import OpenCVCapture, Open3d_visualizer 
  File "/content/CenterHMR/src/utils/demo_utils.py", line 4, in <module>
    import open3d as o3d
  File "/usr/local/lib/python3.6/dist-packages/open3d/__init__.py", line 64, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc++.so.1: cannot open shared object file: No such file or directory"

Regards

**Comment by jbkarle** [comment]
Forgot to mention is Colab Demo output!

**Comment by Arthur151** [comment]
Thanks for the bug report! It has been fixed. Hope you have a good time.

**Comment by jbkarle** [comment]
Thank you for your prompt reply! Good time for you also!
